### PR TITLE
Remove bundled copy of os_volume module

### PR DESCRIPTION
**Pull request by manics**
The relevant PR is included in Ansible 2.3

### CODE REVIEW

**Comment by joshmoore** [comment]
This effectively means that our OS roles would be 2.3+ though, correct?

**Comment by manics** [comment]
I think this is the only one. It should continue to work with Ansible 2.1/2.2 since the new parameter is optional: https://github.com/manics/ansible-role-openstack-volume-storage/blob/2b7f724ced202a0c9263f4cd0a493a99b021eb68/tasks/main.yml#L10

**Comment by joshmoore** [comment]
So release as 1.1.0 and if someone on ansible 2.2 + volume copy complains we say, "bump to ansible 2.3"?

**Comment by manics** [comment]
Sounds fine to me

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
